"""Updating Futures Order model

Revision ID: 3f0acfa12194
Revises: 5c433b0aa598
Create Date: 2024-04-22 23:45:06.527038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0acfa12194'
down_revision = '5c433b0aa598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_size', sa.String(length=128), nullable=True))
        batch_op.drop_column('stop_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stop_price', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('quote_size')

    # ### end Alembic commands ###
