"""Updated Signals model for symbols to trading_pair.

Revision ID: 3ff6ac794960
Revises: c8e116b8ece3
Create Date: 2024-04-15 21:51:00.340451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff6ac794960'
down_revision = 'c8e116b8ece3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aurox_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trading_pair', sa.String(length=30), nullable=True))
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aurox_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('trading_pair')

    # ### end Alembic commands ###
