"""Added creation_origin to FuturePostion to help track the bot vs coinbase UI

Revision ID: 463733216ea3
Revises: 51c7d9a9e724
Create Date: 2024-04-30 21:22:32.037121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463733216ea3'
down_revision = '51c7d9a9e724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_origin', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_position', schema=None) as batch_op:
        batch_op.drop_column('creation_origin')

    # ### end Alembic commands ###
