"""adding is_active to User model

Revision ID: 46551c4adfa3
Revises: 463733216ea3
Create Date: 2024-05-10 06:42:31.721776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46551c4adfa3'
down_revision = '463733216ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
