"""Updating Futures Order model for leverage field

Revision ID: 5b602f1558a0
Revises: 3f0acfa12194
Create Date: 2024-04-23 10:35:20.237449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b602f1558a0'
down_revision = '3f0acfa12194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leverage', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.drop_column('leverage')

    # ### end Alembic commands ###
