"""Renamed CoinbaseFuture model

Revision ID: 5c433b0aa598
Revises: ffec0b35d26a
Create Date: 2024-04-17 20:57:18.387382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c433b0aa598'
down_revision = 'ffec0b35d26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coinbase_future_product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coinbase_future_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('price_change_24h', sa.FLOAT(), nullable=True),
    sa.Column('volume_24h', sa.FLOAT(), nullable=True),
    sa.Column('volume_change_24h', sa.FLOAT(), nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('product_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('contract_expiry', sa.DATETIME(), nullable=True),
    sa.Column('contract_size', sa.FLOAT(), nullable=True),
    sa.Column('contract_root_unit', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), nullable=True),
    sa.Column('trading_disabled', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    # ### end Alembic commands ###
