"""Adding more fields from the List Orders call to Future Orders

Revision ID: 5d098f5d1736
Revises: 9b69f5d61596
Create Date: 2024-04-26 15:04:14.114663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d098f5d1736'
down_revision = '9b69f5d61596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_origin', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.drop_column('creation_origin')

    # ### end Alembic commands ###
