"""Updating futures model

Revision ID: 738911d296f0
Revises: f2e8b764d14d
Create Date: 2024-04-16 21:18:01.484317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738911d296f0'
down_revision = 'f2e8b764d14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coinbase_future', schema=None) as batch_op:
        batch_op.drop_column('base_name')
        batch_op.drop_column('quote_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coinbase_future', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_name', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('base_name', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
