"""Adding more fields from the List Orders call to Future Orders

Revision ID: 8f4d5af7fde1
Revises: 5d098f5d1736
Create Date: 2024-04-28 19:30:58.280414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4d5af7fde1'
down_revision = '5d098f5d1736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_note', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.drop_column('bot_note')

    # ### end Alembic commands ###
