"""Adding order status to Future Orders

Revision ID: 93eca37c4ad1
Revises: fa3100600129
Create Date: 2024-04-24 08:35:59.021252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93eca37c4ad1'
down_revision = 'fa3100600129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_status', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.drop_column('order_status')

    # ### end Alembic commands ###
