"""Adding more fields from the List Orders call to Future Orders

Revision ID: 95b675ef4015
Revises: 93eca37c4ad1
Create Date: 2024-04-24 08:59:40.118275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b675ef4015'
down_revision = '93eca37c4ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_filled_price', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('completion_percentage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('filled_size', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('filled_value', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('is_liquidation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_fill_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('margin_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('number_of_fills', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_fees', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('total_value_after_fees', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('trigger_status', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.drop_column('trigger_status')
        batch_op.drop_column('total_value_after_fees')
        batch_op.drop_column('total_fees')
        batch_op.drop_column('number_of_fills')
        batch_op.drop_column('margin_type')
        batch_op.drop_column('last_fill_time')
        batch_op.drop_column('is_liquidation')
        batch_op.drop_column('filled_value')
        batch_op.drop_column('filled_size')
        batch_op.drop_column('completion_percentage')
        batch_op.drop_column('average_filled_price')

    # ### end Alembic commands ###
