"""Adding more fields from the List Orders call to Future Orders

Revision ID: b18e6a5c8dbb
Revises: 8f4d5af7fde1
Create Date: 2024-04-29 10:35:36.427327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18e6a5c8dbb'
down_revision = '8f4d5af7fde1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futures_order', schema=None) as batch_op:
        batch_op.drop_column('bot_active')

    # ### end Alembic commands ###
