"""Updated the AccountBalance field

Revision ID: b8a98fb94436
Revises: f25f00cda571
Create Date: 2024-05-19 20:55:43.699575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8a98fb94436'
down_revision = 'f25f00cda571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_balance_summary', schema=None) as batch_op:
        batch_op.alter_column('liquidation_buffer_percentage',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_balance_summary', schema=None) as batch_op:
        batch_op.alter_column('liquidation_buffer_percentage',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
