"""Updated fields to nullable.

Revision ID: c8e116b8ece3
Revises: 
Create Date: 2024-04-15 21:48:55.650509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e116b8ece3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aurox_signal', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('signal',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('time_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aurox_signal', schema=None) as batch_op:
        batch_op.alter_column('time_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('signal',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
