"""Updated the HistoricalAuroxSignal to add spot and futures prices

Revision ID: f25f00cda571
Revises: 5d5fccb3092d
Create Date: 2024-05-16 14:51:13.709670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25f00cda571'
down_revision = '5d5fccb3092d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_aurox_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signal_spot_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('future_bid_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('future_ask_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_aurox_signal', schema=None) as batch_op:
        batch_op.drop_column('future_ask_price')
        batch_op.drop_column('future_bid_price')
        batch_op.drop_column('signal_spot_price')

    # ### end Alembic commands ###
