"""Updating futures model

Revision ID: f2e8b764d14d
Revises: 3ff6ac794960
Create Date: 2024-04-16 21:16:20.934666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e8b764d14d'
down_revision = '3ff6ac794960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coinbase_future', schema=None) as batch_op:
        batch_op.drop_column('quote_increment')
        batch_op.drop_column('base_min_size')
        batch_op.drop_column('base_max_size')
        batch_op.drop_column('quote_max_size')
        batch_op.drop_column('venue')
        batch_op.drop_column('quote_min_size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coinbase_future', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_min_size', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('venue', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('quote_max_size', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('base_max_size', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('base_min_size', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('quote_increment', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
