"""removing user_id from balance summary model

Revision ID: ffec0b35d26a
Revises: 1fd30d808dd2
Create Date: 2024-04-17 18:52:16.217058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffec0b35d26a'
down_revision = '1fd30d808dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_balance_summary', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_balance_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
